# Application Name
spring.application.name=mvcpontoeletronico

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pontoeletronico
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Server Configuration
server.port=8081

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.empresa.mvcpontoeletronico=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/MundialCiclo
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/MundialCiclo/protocol/openid-connect/certs

# Keycloak Admin Configuration
keycloak.admin.server-url=http://localhost:8080
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.target-realm=MundialCiclo

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174
